### ISSUE TITLE
Duplicating occurrences

### ISSUE THREAD

**Issue by josteist** [ropensci/paleobioDB#23]
I found a bug that duplicates downloaded occurrences. E.g.

dinos  <- pbdb_occurrences(limit="all", base_name="Dinosauria", show=c("phylo", "ident", "time"))

Or similar calls makes all the downloaded occurrences being duplicated in the 'dinos' array. They're easily found by comparing the occurrence id's
tmpdins = which(duplicated(dinos$oid))

I've contacted the crew at PaleoDB, and they say it's not a server side problem, and that the service call made in the R package does not lead to duplicated records, so it must be a bug in paleobioDB.

best
Jostein

**Comment by mmcclenn** [comment]
I have traced through the code as best I can given my limited familiarity with R, and the problem seems to crop up in the function ".make_data_frame", in the call to "as.data.frame".  The result of this call, which gets assigned to df, has two rows where it ought to have one (reg_list[1] has only one element).

**Comment by SaraVarela** [comment]
Hi Jostein and Michael , 

thanks for the feedbacks!
It is nice to know that people are using the package. 

It was not straightforward to program the dataframe output in a flexible way, allowing blank columns, etc. this was mainly because the first line in the json files from the API does not allways have information for all the fields... well, let's see what is the problem that you might found. 

I am teaching in a summer course in Amsterdam all this week, 
So I will be able to check this out during the next week, to see what happens with .make_data_frame
:-)

However, if you have the time and you feel like, feel free to fork this repo, investigate the potential solution and do a pull request if you manage to fix it. We will appreciate any collaboration! :-)

thanks again, 
cheers, 
Sara

**Comment by SaraVarela** [comment]
Jostein, 

I am quickly checking the issue. yes, our package it is duplicating the records now :-(
This is a new bug that was not there before, it would be related to upgrades in R-packages that we depend on to construct our outputs. 

Meanwhile, if you want to work with your data, just erase the duplicate records from our output dataframe like this:

not_duplicated_query<- raw_query [c(TRUE, FALSE), ]

I will fix the bug in the package next week, 

I hope that this helps, 
best, 
Sara

**Comment by josteist** [comment]
Hi Sara.
I also noticed that something happened during the summer, because in June
this error did not occurr with the exact same call. When I came back after
the summer i reran all my tests and weird numbers popped up. When I found
the error I just removed the duplicated occs from my data before proceeding.

best
J

**Comment by SaraVarela** [comment]
Hi Jostein, 

sorry for not answering before. We fixed the problem long ago. it was a problem of the database itself. 

Now we are having other issues because the database is changing again, so please, use our package from github (because normally it will be updated) and not from the CRAN. 

install.packages("devtools")
library(devtools)
install_github("ropensci/paleobioDB")
library(paleobioDB)

best wishes, 
Sara
